import { Book } from '../../models/book.model';

export const Books: Book[] = [
  {
    bookId: '1a2b3c4d5e6f7g8h9i0j',
    title: 'Dune',
    imgUrl:
      'https://www.elnacional.cat/uploads/s1/16/77/50/00/dune-portada-cartone-foto-raig-verd-mai-mes_1_630x630.jpeg',
    pages: '412',
    size: '5000000',
    year: '1965',
    publisher: 'Chilton Books',
    language: 'English',
    type: 'pdf',
    authors: 'Frank Herbert',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '1a2b3c4d5e6f7g8h9i0j',
      description:
        'Ambientada en un futuro lejano, Dune cuenta la historia de Paul Atreides, un joven heredero de la Casa Atreides, una de las Grandes Casas del imperio interestelar. Cuando su padre, el duque Leto Atreides, recibe la orden de hacerse con el control del desértico planeta Arrakis, única fuente de la valiosa especia melange, Paul y su familia se ven atrapados en una lucha de poder entre casas rivales, los Fremen, los habitantes nativos de Arrakis, y el emperador Padishah Shaddam IV.',
      numberPages: 684,
      numberChapters: 54,
      dimensiones: [5.5, 8.5],
      peso: 1.4,
    },
  },
  {
    bookId: '2b3c4d5e6f7g8h9i0j1a',
    title: 'Neuromancer',
    imgUrl:
      'https://planetadelibrosco0.cdnstatics.com/usuaris/libros/fotos/358/m_libros/357557_portada_neuromante-n-0103-trilogia-de-sprawl-ne_william-gibson_202211141628.jpg',
    pages: '271',
    size: '3000000',
    year: '1984',
    publisher: 'Ace Books',
    language: 'English',
    type: 'pdf',
    authors: 'William Gibson',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '2b3c4d5e6f7g8h9i0j1a',
      description:
        'Tras ser contratado por una misteriosa mujer llamada Molly Millions, Case se une a un grupo de hackers y mercenarios que se adentran en el ciberespacio, una red virtual omnipresente donde se desarrolla gran parte de la vida social y económica.',
      numberPages: 304,
      numberChapters: 26,
      dimensiones: [5.25, 7.75],
      peso: 0.7,
    },
  },
  {
    bookId: '3c4d5e6f7g8h9i0j1a2b',
    title: 'Foundation',
    imgUrl: 'https://www.mrbooks.com/mrbooks/portadas/9788497596763.webp',
    pages: '244',
    size: '3500000',
    year: '1951',
    publisher: 'Gnome Press',
    language: 'English',
    type: 'pdf',
    authors: 'Isaac Asimov',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '3c4d5e6f7g8h9i0j1a2b',
      description: '',
      numberPages: 0,
      numberChapters: 0,
      dimensiones: [],
      peso: 0,
    },
  },
  {
    bookId: '4d5e6f7g8h9i0j1a2b3c',
    title: 'Snow Crash',
    imgUrl:
      'https://images.cdn1.buscalibre.com/fit-in/360x360/94/0e/940e61cee02f6d0bbec62f535175b3f0.jpg',
    pages: '468',
    size: '4500000',
    year: '1992',
    publisher: 'Bantam Books',
    language: 'English',
    type: 'pdf',
    authors: 'Neal Stephenson',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '2b3c4d5e6f7g8h9i0j1a',
      description:
        'En un futuro lejano, el vasto Imperio Galáctico de la humanidad está al borde del colapso. Hari Seldon, un brillante matemático y psicohistoriador, ha desarrollado una ciencia para predecir el futuro con notable exactitud. Prevé la inevitable caída del Imperio y la consiguiente Edad Oscura que durará siglos.',
      numberPages: 252,
      numberChapters: 35,
      dimensiones: [5.25, 8],
      peso: 0.75,
    },
  },
  {
    bookId: '5e6f7g8h9i0j1a2b3c4d',
    title: 'The Left Hand of Darkness',
    imgUrl:
      'https://cdna.artstation.com/p/assets/images/images/019/739/170/large/j-yang-jyang-tlhod-1.jpg?1564797285',
    pages: '304',
    size: '4000000',
    year: '1969',
    publisher: 'Ace Books',
    language: 'English',
    type: 'pdf',
    authors: 'Ursula K. Le Guin',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '5e6f7g8h9i0j1a2b3c4d',
      description:
        'En el gélido planeta de Invierno, donde el clima glacial y la oscuridad perpetua son la norma, habita una sociedad única: los habitantes de Gueden, conocidos como guedenianos, son andróginos, carecen de sexo biológico definido y experimentan periodos de kemmer, donde adoptan temporalmente características masculinas o femeninas.',
      numberPages: 320,
      numberChapters: 22,
      dimensiones: [5.25, 8],
      peso: 0.7,
    },
  },
  {
    bookId: '6f7g8h9i0j1a2b3c4d5e',
    title: 'Hyperion',
    imgUrl:
      'https://imagedelivery.net/QDkyDSqaJI1JEO0MqH_3SQ/8f595e52-25bb-4c2b-6c52-c58c7a90c600/default',
    pages: '482',
    size: '5500000',
    year: '1989',
    publisher: 'Doubleday',
    language: 'English',
    type: 'pdf',
    authors: 'Dan Simmons',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '6f7g8h9i0j1a2b3c4d5e',
      description:
        'En un futuro lejano, la humanidad se ha expandido por la galaxia, habitando planetas y sistemas estelares bajo el dominio del Hegemony of Man, una organización interplanetaria. Sin embargo, un misterioso fenómeno conocido como el Shrike ha comenzado a aparecer en diferentes planetas, sembrando terror y destrucción a su paso.',
      numberPages: 480,
      numberChapters: 46,
      dimensiones: [5.25, 8],
      peso: 1,
    },
  },
  {
    bookId: '7g8h9i0j1a2b3c4d5e6f',
    title: "Ender's Game",
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/93/b3/93b3557e069d5366fa46d5e2920febaf.jpg',
    pages: '324',
    size: '3700000',
    year: '1985',
    publisher: 'Tor Books',
    language: 'English',
    type: 'pdf',
    authors: 'Orson Scott Card',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '7g8h9i0j1a2b3c4d5e6f',
      description:
        'Tras una invasión alienígena que casi acaba con la humanidad, los ejércitos de la Tierra están decididos a prepararse para el próximo ataque. Andrew "Ender" Wiggin, un joven brillante pero problemático, es reclutado en la Escuela de Batalla, un centro de entrenamiento donde los niños superdotados son preparados para convertirse en la próxima generación de líderes militares.',
      numberPages: 324,
      numberChapters: 30,
      dimensiones: [5.25, 8],
      peso: 0.7,
    },
  },
  {
    bookId: '8h9i0j1a2b3c4d5e6f7g',
    title: "The Hitchhiker's Guide to the Galaxy",
    imgUrl:
      'https://uploads-ssl.webflow.com/5f29b3f3cea3ad5a1b369735/5fc3de5d868fa56cc8c2d41e_Hitchikers%20Guide%20to%20the%20Galaxy-p-500.png',
    pages: '216',
    size: '3100000',
    year: '1979',
    publisher: 'Pan Books',
    language: 'English',
    type: 'pdf',
    authors: 'Douglas Adams',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '8h9i0j1a2b3c4d5e6f7g',
      description:
        'La Guía del autoestopista galáctico es una comedia de ciencia ficción de humor negro que sigue las desventuras de Arthur Dent, un inglés normal y corriente, el día en que la Tierra es demolida para dar paso a una carretera de circunvalación hiperespacial. Salvado por su amigo Ford Prefect, que resulta ser un investigador encubierto de la Guía del Autoestopista, Arthur se ve inmerso en el disparatado y a menudo peligroso mundo de los viajes interestelares.',
      numberPages: 192,
      numberChapters: 15,
      dimensiones: [4.25, 7],
      peso: 0.3,
    },
  },
  {
    bookId: '9i0j1a2b3c4d5e6f7g8h',
    title: 'Brave New World',
    imgUrl:
      'https://images.cdn1.buscalibre.com/fit-in/360x360/0a/2c/0a2cee31d416d14bc544c3434570a782.jpg',
    pages: '268',
    size: '3400000',
    year: '1932',
    publisher: 'Chatto & Windus',
    language: 'English',
    type: 'pdf',
    authors: 'Aldous Huxley',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '9i0j1a2b3c4d5e6f7g8h',
      description:
        'Ambientada en el Estado Mundial del siglo XXVII, Brave New World pinta un escalofriante retrato de una sociedad futura en la que la tecnología y el condicionamiento social han erradicado la individualidad, la libertad y las emociones humanas genuinas. Los ciudadanos son modificados genéticamente y condicionados desde su nacimiento para cumplir determinados papeles en una rígida jerarquía social, que garantiza la estabilidad y la felicidad a expensas de la realización personal y el pensamiento crítico.',
      numberPages: 262,
      numberChapters: 18,
      dimensiones: [5.25, 7.75],
      peso: 0.7,
    },
  },
  {
    bookId: '0j1a2b3c4d5e6f7g8h9i',
    title: 'The War of the Worlds',
    imgUrl:
      'https://fcs-img.s3.amazonaws.com/1ebda62b-7f02-4fab-8e39-a5e6016ae6b4/2658693b-2fdb-4045-a993-aeb501427ceb/XL.jpg',
    pages: '192',
    size: '2800000',
    year: '1898',
    publisher: 'William Heinemann',
    language: 'English',
    type: 'pdf',
    authors: 'H.G. Wells',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '0j1a2b3c4d5e6f7g8h9i',
      description:
        'A finales del siglo XIX, una oleada de misteriosos cilindros se estrella en la campiña inglesa, anunciando la llegada de hostiles invasores extraterrestres procedentes de Marte. Cuando los marcianos emergen de sus naves, armados con mortíferos rayos de calor y máquinas de combate montadas en trípodes, desencadenan un devastador ataque contra la humanidad, arrasando pueblos y ciudades y provocando el pánico y la destrucción generalizados.',
      numberPages: 208,
      numberChapters: 20,
      dimensiones: [5, 7.5],
      peso: 0.5,
    },
  },
  {
    bookId: '1a2b3c4d5e',
    title: 'Don Quixote',
    imgUrl:
      'https://images.cdn1.buscalibre.com/fit-in/360x360/a6/18/a618be10eae5c2a608ec6e22e6917e29.jpg',
    pages: '992',
    size: '14500000',
    year: '1605',
    publisher: 'Francisco de Robles',
    language: 'Spanish',
    type: 'pdf',
    authors: 'Miguel de Cervantes',
    category: 'Literatura Universal',
    detail: {
      bookId: '1a2b3c4d5e6f7g8h9i0j1a',
      description:
        'La historia del ingenioso hidalgo Don Quijote de la Mancha y su escudero Sancho Panza.',
      numberPages: 992,
      numberChapters: 126,
      dimensiones: [5.5, 8.5],
      peso: 1.2,
    },
  },
  {
    bookId: '2a3b4c5d6e7f8g9h0i1j',
    title: 'War and Peace',
    imgUrl: 'https://m.media-amazon.com/images/I/51+7S5hJ3DL._SY445_SX342_.jpg',
    pages: '1225',
    size: '17500000',
    year: '1869',
    publisher: 'The Russian Messenger',
    language: 'Russian',
    type: 'pdf',
    authors: 'Leo Tolstoy',
    category: 'Literatura Universal',
    detail: {
      bookId: '2a3b4c5d6e7f8g9h0i1j2a',
      description:
        'Una obra maestra de la literatura que narra la invasión napoleónica de Rusia.',
      numberPages: 1225,
      numberChapters: 365,
      dimensiones: [6, 9],
      peso: 1.5,
    },
  },
  {
    bookId: '3a4b5c6d7e8f9g0h1i2j',
    title: 'Pride and Prejudice',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/17/d7/17d74188e02d9230386dc5356bbe5330.jpg',
    pages: '279',
    size: '4500000',
    year: '1813',
    publisher: 'T. Egerton, Whitehall',
    language: 'English',
    type: 'pdf',
    authors: 'Jane Austen',
    category: 'Literatura Universal',
    detail: {
      bookId: '3a4b5c6d7e8f9g0h1i2j3a',
      description: 'Una clásica novela de romance y crítica social.',
      numberPages: 279,
      numberChapters: 61,
      dimensiones: [5, 7.8],
      peso: 0.6,
    },
  },
  {
    bookId: '4a5b6c7d8e9f0g1h2i3j',
    title: 'Moby Dick',
    imgUrl:
      'https://www.tornamesa.co/imagenes_grandes/9788499/978849908655.GIF',
    pages: '635',
    size: '9000000',
    year: '1851',
    publisher: 'Harper & Brothers',
    language: 'English',
    type: 'pdf',
    authors: 'Herman Melville',
    category: 'Literatura Universal',
    detail: {
      bookId: '4a5b6c7d8e9f0g1h2i3j4a',
      description:
        'La épica historia de la obsesión del capitán Ahab por la ballena blanca Moby Dick.',
      numberPages: 635,
      numberChapters: 135,
      dimensiones: [5.5, 8.5],
      peso: 1.1,
    },
  },
  {
    bookId: '5a6b7c8d9e0f1g2h3i4j',
    title: 'The Odyssey',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/ef/05/ef05223eb3fa0505f842bee366534de4.jpg',
    pages: '541',
    size: '8500000',
    year: '8th century BC',
    publisher: 'Ancient Greece',
    language: 'Greek',
    type: 'pdf',
    authors: 'Homer',
    category: 'Literatura Universal',
    detail: {
      bookId: '5a6b7c8d9e0f1g2h3i4j5a',
      description: 'El épico viaje de Odiseo de vuelta a su hogar en Ítaca.',
      numberPages: 541,
      numberChapters: 24,
      dimensiones: [5.5, 8.5],
      peso: 0.9,
    },
  },
  {
    bookId: '6a7b8c9d0e1f2g3h4i5j',
    title: 'To Kill a Mockingbird',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/55/9b/559bc656b59bdca8fb352cc168495f5e.jpg',
    pages: '324',
    size: '5000000',
    year: '1960',
    publisher: 'J.B. Lippincott & Co.',
    language: 'English',
    type: 'pdf',
    authors: 'Harper Lee',
    category: 'Literatura Universal',
    detail: {
      bookId: '6a7b8c9d0e1f2g3h4i5j6a',
      description:
        'Una poderosa historia sobre la injusticia racial en el sur de Estados Unidos.',
      numberPages: 324,
      numberChapters: 31,
      dimensiones: [5.3, 8],
      peso: 0.7,
    },
  },
  {
    bookId: '7a8b9c0d1e2f3g4h5i6j',
    title: '1984',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/0f/4c/0f4c4009691a0b3058d6ccdbe22111f1.jpg',
    pages: '328',
    size: '4900000',
    year: '1949',
    publisher: 'Secker & Warburg',
    language: 'English',
    type: 'pdf',
    authors: 'George Orwell',
    category: 'Literatura Universal',
    detail: {
      bookId: '7a8b9c0d1e2f3g4h5i6j7a',
      description:
        'Una distopía sobre un futuro totalitario y la vigilancia masiva.',
      numberPages: 328,
      numberChapters: 24,
      dimensiones: [5.2, 8],
      peso: 0.8,
    },
  },
  {
    bookId: '8a9b0c1d2e3f4g5h6i7j',
    title: 'The Great Gatsby',
    imgUrl: 'https://www.mrbooks.com/mrbooks/portadas/9789583065064.webp',
    pages: '180',
    size: '3500000',
    year: '1925',
    publisher: "Charles Scribner's Sons",
    language: 'English',
    type: 'pdf',
    authors: 'F. Scott Fitzgerald',
    category: 'Literatura Universal',
    detail: {
      bookId: '8a9b0c1d2e3f4g5h6i7j8a',
      description:
        'Una crítica a la sociedad americana de los años 20 a través de la historia de Jay Gatsby.',
      numberPages: 180,
      numberChapters: 9,
      dimensiones: [5.2, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '9a0b1c2d3e4f5g6h7i8j',
    title: 'Les Misérables',
    imgUrl:
      'https://image.cdn0.buscalibre.com/5b5ae2451dc861bc548b4567.__RS360x360__.jpg',
    pages: '1463',
    size: '21000000',
    year: '1862',
    publisher: 'A. Lacroix, Verboeckhoven & Cie.',
    language: 'French',
    type: 'pdf',
    authors: 'Victor Hugo',
    category: 'Literatura Universal',
    detail: {
      bookId: '9a0b1c2d3e4f5g6h7i8j9a',
      description:
        'La épica historia de la vida y sufrimiento en la Francia del siglo XIX.',
      numberPages: 1463,
      numberChapters: 365,
      dimensiones: [6, 9],
      peso: 2.0,
    },
  },
  {
    bookId: '1m2n3o4p5q6r7s8t9u0v',
    title: 'The Hound of the Baskervilles',
    imgUrl:
      'https://covers.storytel.com/jpg-640/9781398823884.25d6b372-82b9-45dd-b7f4-37e7e69a38ad?optimize=high&quality=70',
    pages: '256',
    size: '3200000',
    year: '1902',
    publisher: 'George Newnes',
    language: 'English',
    type: 'pdf',
    authors: 'Arthur Conan Doyle',
    category: 'Misterio',
    detail: {
      bookId: '1m2n3o4p5q6r7s8t9u0v1a',
      description:
        'Una de las historias más famosas de Sherlock Holmes, en la que investiga la leyenda de un perro fantasmal.',
      numberPages: 256,
      numberChapters: 15,
      dimensiones: [5.5, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '2m3n4o5p6q7r8s9t0u1v',
    title: 'Gone Girl',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/a3/33/a33304cbc1352790e0135ab2cebbb1d4.jpg',
    pages: '432',
    size: '5700000',
    year: '2012',
    publisher: 'Crown Publishing Group',
    language: 'English',
    type: 'pdf',
    authors: 'Gillian Flynn',
    category: 'Misterio',
    detail: {
      bookId: '2m3n4o5p6q7r8s9t0u1v2a',
      description:
        'Una oscura historia sobre el misterio de la desaparición de Amy Dunne y las mentiras que rodean su matrimonio.',
      numberPages: 432,
      numberChapters: 45,
      dimensiones: [5.8, 8.3],
      peso: 0.7,
    },
  },
  {
    bookId: '3m4n5o6p7q8r9s0t1u2v',
    title: 'The Girl with the Dragon Tattoo',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/d0/79/d079885d6ce29f13cb29c281e3245f80.jpg',
    pages: '465',
    size: '6800000',
    year: '2005',
    publisher: 'Norstedts Förlag',
    language: 'Swedish',
    type: 'pdf',
    authors: 'Stieg Larsson',
    category: 'Misterio',
    detail: {
      bookId: '3m4n5o6p7q8r9s0t1u2v3a',
      description:
        'La primera novela de la trilogía Millennium, centrada en la investigación de la desaparición de Harriet Vanger.',
      numberPages: 465,
      numberChapters: 29,
      dimensiones: [6, 9],
      peso: 0.8,
    },
  },
  {
    bookId: '4m5n6o7p8q9r0s1t2u3v',
    title: 'The Da Vinci Code',
    imgUrl:
      'https://images.cdn2.buscalibre.com/fit-in/360x360/3e/37/3e37e785a8c5864b102976f3960dc015.jpg',
    pages: '689',
    size: '7800000',
    year: '2003',
    publisher: 'Doubleday',
    language: 'English',
    type: 'pdf',
    authors: 'Dan Brown',
    category: 'Misterio',
    detail: {
      bookId: '4m5n6o7p8q9r0s1t2u3v4a',
      description:
        'Un thriller que sigue a Robert Langdon y Sophie Neveu mientras descifran códigos ocultos y secretos del cristianismo.',
      numberPages: 689,
      numberChapters: 105,
      dimensiones: [5.8, 8.3],
      peso: 0.9,
    },
  },
  {
    bookId: '5m6n7o8p9q0r1s2t3u4v',
    title: 'Big Little Lies',
    imgUrl:
      'https://images.cdn2.buscalibre.com/fit-in/360x360/15/3d/153dc117086de9018cb7c72c5f14ccf1.jpg',
    pages: '460',
    size: '6900000',
    year: '2014',
    publisher: 'Penguin Group',
    language: 'English',
    type: 'pdf',
    authors: 'Liane Moriarty',
    category: 'Misterio',
    detail: {
      bookId: '5m6n7o8p9q0r1s2t3u4v5a',
      description:
        'Una historia de intriga y secretos que se revelan tras una trágica muerte en una comunidad escolar.',
      numberPages: 460,
      numberChapters: 70,
      dimensiones: [5.5, 8.5],
      peso: 0.8,
    },
  },
  {
    bookId: '6m7n8o9p0q1r2s3t4u5v',
    title: 'Rebecca',
    imgUrl:
      'https://images.cdn1.buscalibre.com/fit-in/360x360/38/16/3816104ffd3c7c937e799f1c6f156f06.jpg',
    pages: '448',
    size: '6200000',
    year: '1938',
    publisher: 'Victor Gollancz',
    language: 'English',
    type: 'pdf',
    authors: 'Daphne du Maurier',
    category: 'Misterio',
    detail: {
      bookId: '6m7n8o9p0q1r2s3t4u5v6a',
      description:
        'La historia de una joven novia que lucha por adaptarse a la vida en la mansión Manderley y a la sombra de la primera esposa de su marido.',
      numberPages: 448,
      numberChapters: 27,
      dimensiones: [5.4, 8],
      peso: 0.75,
    },
  },
  {
    bookId: '7m8n9o0p1q2r3s4t5u6v',
    title: 'The Silence of the Lambs',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/28/33/2833015322dd8849cf5b355e45910398.jpg',
    pages: '367',
    size: '5500000',
    year: '1988',
    publisher: "St. Martin's Press",
    language: 'English',
    type: 'pdf',
    authors: 'Thomas Harris',
    category: 'Misterio',
    detail: {
      bookId: '7m8n9o0p1q2r3s4t5u6v7a',
      description:
        'La agente del FBI Clarice Starling debe entrevistar al encarcelado Dr. Hannibal Lecter para capturar a otro asesino en serie.',
      numberPages: 367,
      numberChapters: 61,
      dimensiones: [5.5, 8.2],
      peso: 0.7,
    },
  },
  {
    bookId: '8m9n0o1p2q3r4s5t6u7v',
    title: 'The Maltese Falcon',
    imgUrl:
      'https://images.cdn1.buscalibre.com/fit-in/360x360/ab/1b/ab1b1e4c170bb7adf86884847cb35a78.jpg',
    pages: '217',
    size: '3200000',
    year: '1930',
    publisher: 'Alfred A. Knopf',
    language: 'English',
    type: 'pdf',
    authors: 'Dashiell Hammett',
    category: 'Misterio',
    detail: {
      bookId: '8m9n0o1p2q3r4s5t6u7v8a',
      description:
        'El detective Sam Spade se ve envuelto en la búsqueda de una estatuilla robada de incalculable valor.',
      numberPages: 217,
      numberChapters: 20,
      dimensiones: [5.3, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '9m0n1o2p3q4r5s6t7u8v',
    title: 'The Girl on the Train',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/df/cd/dfcd2277de6ee620be6318cada7a9174.jpg',
    pages: '395',
    size: '5200000',
    year: '2015',
    publisher: 'Riverhead Books',
    language: 'English',
    type: 'pdf',
    authors: 'Paula Hawkins',
    category: 'Misterio',
    detail: {
      bookId: '9m0n1o2p3q4r5s6t7u8v9a',
      description:
        'Rachel, una mujer divorciada, se ve envuelta en un misterio tras presenciar algo extraño desde el tren.',
      numberPages: 395,
      numberChapters: 43,
      dimensiones: [5.7, 8.4],
      peso: 0.7,
    },
  },
  {
    bookId: '1f2g3h4i5j6k7l8m9n0o',
    title: 'The Hobbit',
    imgUrl:
      'https://images.cdn3.buscalibre.com/fit-in/360x360/e2/5c/e25cf09c898ddcfebdfa076dcc1d0ac8.jpg',
    pages: '310',
    size: '4800000',
    year: '1937',
    publisher: 'George Allen & Unwin',
    language: 'English',
    type: 'pdf',
    authors: 'J.R.R. Tolkien',
    category: 'Fantasía',
    detail: {
      bookId: '1f2g3h4i5j6k7l8m9n0o1a',
      description:
        'La historia de Bilbo Baggins, un hobbit que emprende una aventura épica para ayudar a un grupo de enanos a recuperar su hogar.',
      numberPages: 310,
      numberChapters: 19,
      dimensiones: [5.5, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '2f3g4h5i6j7k8l9m0n1o',
    title: "Harry Potter and the Sorcerer's Stone",
    imgUrl: 'https://m.media-amazon.com/images/I/51Ppi-8kISL._SY445_SX342_.jpg',
    pages: '309',
    size: '4600000',
    year: '1997',
    publisher: 'Bloomsbury',
    language: 'English',
    type: 'pdf',
    authors: 'J.K. Rowling',
    category: 'Fantasía',
    detail: {
      bookId: '2f3g4h5i6j7k8l9m0n1o2a',
      description:
        'El primer libro de la serie Harry Potter, donde Harry descubre que es un mago y comienza su educación en Hogwarts.',
      numberPages: 309,
      numberChapters: 17,
      dimensiones: [5.5, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '3f4g5h6i7j8k9l0m1n2o',
    title: 'A Game of Thrones',
    imgUrl:
      'https://images.cdn1.buscalibre.com/fit-in/360x360/84/17/8417346e2bfd353658a87834d085170d.jpg',
    pages: '694',
    size: '10500000',
    year: '1996',
    publisher: 'Bantam Books',
    language: 'English',
    type: 'pdf',
    authors: 'George R.R. Martin',
    category: 'Fantasía',
    detail: {
      bookId: '3f4g5h6i7j8k9l0m1n2o3a',
      description:
        'El primer libro de la serie Canción de Hielo y Fuego, que narra la lucha por el trono de hierro en un mundo de fantasía medieval.',
      numberPages: 694,
      numberChapters: 73,
      dimensiones: [6, 9],
      peso: 1.2,
    },
  },
  {
    bookId: '4f5g6h7i8j9k0l1m2n3o',
    title: 'The Name of the Wind',
    imgUrl:
      'https://grimoakpress.com/cdn/shop/files/cover-notw-fc.jpg?v=1706902909&width=823',
    pages: '662',
    size: '9500000',
    year: '2007',
    publisher: 'DAW Books',
    language: 'English',
    type: 'pdf',
    authors: 'Patrick Rothfuss',
    category: 'Fantasía',
    detail: {
      bookId: '4f5g6h7i8j9k0l1m2n3o4a',
      description:
        'La historia de Kvothe, un hombre legendario que narra su vida y aventuras desde su niñez hasta la edad adulta.',
      numberPages: 662,
      numberChapters: 92,
      dimensiones: [6, 9],
      peso: 1.1,
    },
  },
  {
    bookId: '5f6g7h8i9j0k1l2m3n4o',
    title: 'The Way of Kings',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659905828i/7235533.jpg',
    pages: '1007',
    size: '16000000',
    year: '2010',
    publisher: 'Tor Books',
    language: 'English',
    type: 'pdf',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '5f6g7h8i9j0k1l2m3n4o5a',
      description:
        'El primer libro de la serie El Archivo de las Tormentas, que sigue a varios personajes en un mundo asolado por tormentas mágicas.',
      numberPages: 1007,
      numberChapters: 75,
      dimensiones: [6.5, 9.5],
      peso: 1.5,
    },
  },
  {
    bookId: '6f7g8h9i0j1k2l3m4n5o',
    title: 'Mistborn: The Final Empire',
    imgUrl: 'https://images1.penguinrandomhouse.com/cover/9788498726138',
    pages: '541',
    size: '8000000',
    year: '2006',
    publisher: 'Tor Books',
    language: 'English',
    type: 'pdf',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '6f7g8h9i0j1k2l3m4n5o6a',
      description:
        'El primer libro de la trilogía Nacidos de la Bruma, que sigue a un grupo de rebeldes que planea derrocar a un imperio inmortal.',
      numberPages: 541,
      numberChapters: 38,
      dimensiones: [6, 9],
      peso: 0.9,
    },
  },
  {
    bookId: '7f8g9h0i1j2k3l4m5n6o',
    title: 'The Lies of Locke Lamora',
    imgUrl:
      'https://www.gollancz.co.uk/wp-content/uploads/2018/08/hbg-title-9781409133872-72.jpg?w=450',
    pages: '722',
    size: '11000000',
    year: '2006',
    publisher: 'Bantam Spectra',
    language: 'English',
    type: 'pdf',
    authors: 'Scott Lynch',
    category: 'Fantasía',
    detail: {
      bookId: '7f8g9h0i1j2k3l4m5n6o7a',
      description:
        'La historia de un ladrón maestro en la ciudad de Camorr, que se enfrenta a peligros y traiciones en su intento de robar a los ricos.',
      numberPages: 722,
      numberChapters: 44,
      dimensiones: [6, 9],
      peso: 1.0,
    },
  },
  {
    bookId: '8f9g0h1i2j3k4l5m6n7o',
    title: 'The Eye of the World',
    imgUrl:
      'https://dragonmount.com/uploads/monthly_2020_06/2022627099_eotw-trade2(1).jpg.e119e9221dc1418e2ea16fdf9cbe24bd.jpg',
    pages: '782',
    size: '12000000',
    year: '1990',
    publisher: 'Tor Books',
    language: 'English',
    type: 'pdf',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '8f9g0h1i2j3k4l5m6n7o8a',
      description:
        'El primer libro de la serie La Rueda del Tiempo, que sigue a un grupo de jóvenes que se ven envueltos en una lucha épica contra el Oscuro.',
      numberPages: 782,
      numberChapters: 53,
      dimensiones: [6, 9],
      peso: 1.2,
    },
  },
  {
    bookId: '9f0g1h2i3j4k5l6m7n8o',
    title: 'The Witcher: The Last Wish',
    imgUrl:
      'https://www.estorilbooks.co.za/wp-content/uploads/2022/01/SCI-FI-73.png',
    pages: '288',
    size: '4200000',
    year: '1993',
    publisher: 'SuperNOWA',
    language: 'Polish',
    type: 'pdf',
    authors: 'Andrzej Sapkowski',
    category: 'Fantasía',
    detail: {
      bookId: '9f0g1h2i3j4k5l6m7n8o9a',
      description:
        'Una colección de relatos que presenta a Geralt de Rivia, un cazador de monstruos conocido como brujo.',
      numberPages: 288,
      numberChapters: 7,
      dimensiones: [5.5, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '2b3c4d5e6f7g8h9i0j1a',
    title: 'Jane Eyre',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1692725440i/197321006.jpg',
    pages: '500',
    size: '2500000',
    year: '1847',
    publisher: 'Smith, Elder & Co.',
    language: 'English',
    type: 'pdf',
    authors: 'Charlotte Brontë',
    category: 'Romance',
    detail: {
      bookId: '2b3c4d5e6f7g8h9i0j1a',
      description:
        'Jane Eyre is a novel by English writer Charlotte Brontë. It was published on 16 October 1847 under the pen name "Currer Bell". Primarily a bildungsroman, Jane Eyre follows the emotions and experiences of its eponymous heroine, including her growth to adulthood and her love for Mr. Rochester.',
      numberPages: 500,
      numberChapters: 38,
      dimensiones: [6, 9],
      peso: 1.1,
    },
  },
  {
    bookId: '3c4d5e6f7g8h9',
    title: 'Wuthering Heights',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388212715i/6185.jpg',
    pages: '416',
    size: '2300000',
    year: '1847',
    publisher: 'Thomas Cautley Newby',
    language: 'English',
    type: 'pdf',
    authors: 'Emily Brontë',
    category: 'Romance',
    detail: {
      bookId: '3c4d5e6f7g8h9i0j1a2b',
      description:
        'Wuthering Heights is the only finished novel by Emily Brontë, written between October 1845 and June 1846, and published in 1847 under the pseudonym "Ellis Bell". It is now considered a classic of English literature.',
      numberPages: 416,
      numberChapters: 34,
      dimensiones: [5.5, 8.5],
      peso: 0.85,
    },
  },
  {
    bookId: '4d5e6f7g8h9i0j1a2b3c',
    title: 'Gone with the Wind',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1551144577i/18405.jpg',
    pages: '1037',
    size: '3000000',
    year: '1936',
    publisher: 'Macmillan Publishers',
    language: 'English',
    type: 'pdf',
    authors: 'Margaret Mitchell',
    category: 'Romance',
    detail: {
      bookId: '4d5e6f7g8h9i0j1a2b3c',
      description:
        'Gone with the Wind is a novel by American writer Margaret Mitchell, first published in 1936. The story is set in Clayton County and Atlanta, both in Georgia, during the American Civil War and Reconstruction Era.',
      numberPages: 1037,
      numberChapters: 63,
      dimensiones: [6, 9],
      peso: 1.8,
    },
  },
  {
    bookId: '5e6f7g8h9i0j1',
    title: 'The Notebook',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1483183484i/33648131.jpg',
    pages: '214',
    size: '1800000',
    year: '1996',
    publisher: 'Warner Books',
    language: 'English',
    type: 'pdf',
    authors: 'Nicholas Sparks',
    category: 'Romance',
    detail: {
      bookId: '5e6f7g8h9i0j1a2b3c4d',
      description:
        'The Notebook is a 1996 romantic novel by American novelist Nicholas Sparks, based on a true story. The novel was later adapted into a popular film of the same name, released in 2004.',
      numberPages: 214,
      numberChapters: 18,
      dimensiones: [5.25, 8],
      peso: 0.75,
    },
  },
  {
    bookId: '6f7g8h9i0j1',
    title: 'Me Before You',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1665087720i/17347634.jpg',
    pages: '480',
    size: '2200000',
    year: '2012',
    publisher: 'Penguin Books',
    language: 'English',
    type: 'pdf',
    authors: 'Jojo Moyes',
    category: 'Romance',
    detail: {
      bookId: '6f7g8h9i0j1a2b3c4d5e',
      description:
        'Me Before You is a romance novel written by Jojo Moyes. It was first published on 5 January 2012 in the United Kingdom. A sequel titled After You was released on 29 September 2015 through Pamela Dorman Books.',
      numberPages: 480,
      numberChapters: 27,
      dimensiones: [5.5, 8.5],
      peso: 0.95,
    },
  },
  {
    bookId: '7g8h9i0j1a2b3c4d',
    title: 'Outlander',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659086907i/10964.jpg',
    pages: '850',
    size: '2800000',
    year: '1991',
    publisher: 'Delacorte Press',
    language: 'English',
    type: 'pdf',
    authors: 'Diana Gabaldon',
    category: 'Romance',
    detail: {
      bookId: '7g8h9i0j1a2b3c4d5e6f',
      description:
        'Outlander is a novel by American author Diana Gabaldon. It is the first in a series of eight historical multi-genre novels. Published in 1991, it focuses on the 20th-century British woman Claire Randall, who time travels to 18th-century Scotland and finds adventure and romance with the dashing Highland warrior Jamie Fraser.',
      numberPages: 850,
      numberChapters: 41,
      dimensiones: [6, 9],
      peso: 1.4,
    },
  },
  {
    bookId: '1a2b3',
    title: 'The Republic',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386925655i/30289.jpg',
    pages: '416',
    size: '2200000',
    year: '380 BC',
    publisher: 'Penguin Classics',
    language: 'English',
    type: 'pdf',
    authors: 'Plato',
    category: 'Philosophy',
    detail: {
      bookId: '1a2b3c4d5e6f7g8h9i0j',
      description:
        'The Republic is a Socratic dialogue, written by Plato around 380 BC, concerning justice, the order and character of the just city-state and the just man.',
      numberPages: 416,
      numberChapters: 10,
      dimensiones: [5.5, 8.5],
      peso: 0.8,
    },
  },
  {
    bookId: '2b3c4d',
    title: 'Nicomachean Ethics',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1520339295i/19068.jpg',
    pages: '352',
    size: '1800000',
    year: '340 BC',
    publisher: 'Oxford University Press',
    language: 'English',
    type: 'pdf',
    authors: 'Aristotle',
    category: 'Philosophy',
    detail: {
      bookId: '2b3c4d5e6f7g8h9i0j1a',
      description:
        'Nicomachean Ethics is a work by Aristotle that plays a prominent role in defining Aristotelian ethics.',
      numberPages: 352,
      numberChapters: 10,
      dimensiones: [5.5, 8.5],
      peso: 0.75,
    },
  },
  {
    bookId: '3c4d5e',
    title: 'Critique of Pure Reason',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348663530i/18288.jpg',
    pages: '856',
    size: '2900000',
    year: '1781',
    publisher: 'Cambridge University Press',
    language: 'English',
    type: 'pdf',
    authors: 'Immanuel Kant',
    category: 'Philosophy',
    detail: {
      bookId: '3c4d5e6f7g8h9i0j1a2b',
      description:
        'Critique of Pure Reason is a cornerstone of Western philosophy, in which Kant outlines his theory of knowledge and his concept of transcendental idealism.',
      numberPages: 856,
      numberChapters: 12,
      dimensiones: [6, 9],
      peso: 1.5,
    },
  },
  {
    bookId: '4d5e6fc',
    title: 'Being and Time',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1298438455i/92307.jpg',
    pages: '589',
    size: '2400000',
    year: '1927',
    publisher: 'Harper & Row',
    language: 'English',
    type: 'pdf',
    authors: 'Martin Heidegger',
    category: 'Philosophy',
    detail: {
      bookId: '4d5e6f7g8h9i0j1a2b3c',
      description:
        'Being and Time is a fundamental text in existential philosophy, exploring the concept of Being in a temporally conscious existence.',
      numberPages: 589,
      numberChapters: 18,
      dimensiones: [6, 9],
      peso: 1.2,
    },
  },
  {
    bookId: '5e6f4d',
    title: 'Beyond Good and Evil',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388607391i/12321.jpg',
    pages: '240',
    size: '1700000',
    year: '1886',
    publisher: 'Penguin Classics',
    language: 'English',
    type: 'pdf',
    authors: 'Friedrich Nietzsche',
    category: 'Philosophy',
    detail: {
      bookId: '5e6f7g8h9i0j1a2b3c4d',
      description:
        'Beyond Good and Evil is a comprehensive statement of Nietzsche\'s mature philosophy, in which he focuses on the concept of "will to power".',
      numberPages: 240,
      numberChapters: 12,
      dimensiones: [5, 8],
      peso: 0.6,
    },
  },
  {
    bookId: '6f74d5e',
    title: 'Meditations',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1421618636i/30659.jpg',
    pages: '304',
    size: '1500000',
    year: '180',
    publisher: 'Penguin Classics',
    language: 'English',
    type: 'pdf',
    authors: 'Marcus Aurelius',
    category: 'Philosophy',
    detail: {
      bookId: '6f7g8h9i0j1a2b3c4d5e',
      description:
        'Meditations is a series of personal writings by Marcus Aurelius, Roman Emperor, setting forth his ideas on Stoic philosophy.',
      numberPages: 304,
      numberChapters: 12,
      dimensiones: [5, 8],
      peso: 0.5,
    },
  },
  {
    bookId: '7g8he6f',
    title: 'Phenomenology of Spirit',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1425522818i/9454.jpg',
    pages: '640',
    size: '2600000',
    year: '1807',
    publisher: 'Oxford University Press',
    language: 'English',
    type: 'pdf',
    authors: 'Georg Wilhelm Friedrich Hegel',
    category: 'Philosophy',
    detail: {
      bookId: '7g8h9i0j1a2b3c4d5e6f',
      description:
        "Phenomenology of Spirit is one of Hegel's most important works, exploring the development of human consciousness.",
      numberPages: 640,
      numberChapters: 15,
      dimensiones: [6, 9],
      peso: 1.3,
    },
  },
  {
    bookId: '8h9i0j5e6f7g',
    title: 'The Second Sex',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327978178i/457264.jpg',
    pages: '800',
    size: '3200000',
    year: '1949',
    publisher: 'Vintage Books',
    language: 'English',
    type: 'pdf',
    authors: 'Simone de Beauvoir',
    category: 'Philosophy',
    detail: {
      bookId: '8h9i0j1a2b3c4d5e6f7g',
      description:
        'The Second Sex is a foundational tract in contemporary feminism, discussing the treatment of women throughout history.',
      numberPages: 800,
      numberChapters: 24,
      dimensiones: [6, 9],
      peso: 1.4,
    },
  },
  {
    bookId: '2b3c4d5e6f7gi0j1a',
    title: 'Mistborn: The Final Empire',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1588548480i/53321665.jpg',
    pages: '541',
    size: '2100000',
    year: '2006',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '2b3c4d5e6f7g8h9i0j1a',
      description:
        "Where ash falls from the sky, and mist dominates the night, evil cloaks the land and stifles all life. Criminal mastermind Kelsier teaches Allomancy, the magic of metals, to another Mistborn, urchin Vin 16. The unlikely heroine is distracted by rich Venture heir Elend. Can Kelsier's thieving crew take on the tyrant Lord Ruler and bring back colour to their world?",
      numberPages: 541,
      numberChapters: 38,
      dimensiones: [5.5, 8.2],
      peso: 0.7,
    },
  },
  {
    bookId: '3a2b',
    title: 'Elantris',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1475740953i/68427.jpg',
    pages: '638',
    size: '2600000',
    year: '2005',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '3c4d5e6f7g8h9i0j1a2b',
      description:
        'Elantris was the capital of Arelon: gigantic, beautiful, literally radiant, filled with benevolent beings who used their powerful magical abilities for the benefit of all. Yet each of these demigods was once an ordinary person until touched by the mysterious transforming power of the Shaod. Ten years ago, without warning, the magic failed. Elantrians became wizened, leper-like, powerless creatures, and Elantris itself dark, filthy, and crumbling.',
      numberPages: 638,
      numberChapters: 62,
      dimensiones: [6, 9],
      peso: 1.2,
    },
  },
  {
    bookId: '42b3c',
    title: 'Warbreaker',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1240256182i/1268479.jpg',
    pages: '592',
    size: '2400000',
    year: '2009',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '4d5e6f7g8h9i0j1a2b3c',
      description:
        "From #1 New York Times bestselling author Brandon Sanderson, Warbreaker is the story of two sisters, who happen to be princesses, the God King one of them has to marry, the lesser god who doesn't like his job, and the immortal who's still trying to undo the mistakes he made hundreds of years ago.",
      numberPages: 592,
      numberChapters: 59,
      dimensiones: [6.1, 9.2],
      peso: 1.1,
    },
  },
  {
    bookId: 'b3c4d',
    title: 'Words of Radiance',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659905768i/17332218.jpg',
    pages: '1088',
    size: '4600000',
    year: '2014',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '5e6f7g8h9i0j1a2b3c4d',
      description:
        'Expected by his enemies to die the miserable death of a military slave, Kaladin survived to be given command of the royal bodyguards, a controversial first for a low-status darkeyes. Now he must protect the king and Dalinar from every common peril as well as the distinctly uncommon threat of the Assassin, all while secretly struggling to master remarkable new powers that are somehow linked to his honorspren, Syl.',
      numberPages: 1088,
      numberChapters: 89,
      dimensiones: [6.1, 9.2],
      peso: 1.8,
    },
  },
  {
    bookId: '6f7e',
    title: 'Oathbringer',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654573897i/34002132.jpg',
    pages: '1248',
    size: '5000000',
    year: '2017',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '6f7g8h9i0j1a2b3c4d5e',
      description:
        'In Oathbringer, the third volume of the New York Times bestselling Stormlight Archive, humanity faces a new Desolation with the return of the Voidbringers, a foe with numbers as great as their thirst for vengeance.',
      numberPages: 1248,
      numberChapters: 122,
      dimensiones: [6.1, 9.2],
      peso: 2.0,
    },
  },
  {
    bookId: '7g8h9i0j1a2b3c4d5e6f',
    title: 'Skyward',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1531845177i/36642458.jpg',
    pages: '528',
    size: '2100000',
    year: '2018',
    publisher: 'Delacorte Press',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Ciencia Ficción',
    detail: {
      bookId: '7g8h9i0j1a2b3c4d5e6f',
      description:
        'Defeated, crushed, and driven almost to extinction, the remnants of the human race are trapped on a planet that is constantly attacked by mysterious alien starfighters. Spensa, a teenage girl living among them, longs to be a pilot. When she discovers the wreckage of an ancient ship, she realizes this dream might be possible—assuming she can repair the ship, navigate flight school, and (perhaps most importantly) persuade the strange machine to help her. Because this ship, uniquely, appears to have a soul.',
      numberPages: 528,
      numberChapters: 44,
      dimensiones: [6.1, 9.2],
      peso: 1.0,
    },
  },
  {
    bookId: '8h9ig',
    title: 'Mistborn: The Well of Ascension',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1619538925i/68429.jpg',
    pages: '781',
    size: '3000000',
    year: '2007',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Brandon Sanderson',
    category: 'Fantasía',
    detail: {
      bookId: '8h9i0j1a2b3c4d5e6f7g',
      description:
        'The impossible has been accomplished. The Lord Ruler—the man who claimed to be god incarnate and brutally ruled the world for a thousand years—has been vanquished. But Kelsier, the hero who masterminded that triumph, is dead too, and now the awesome task of building a new world has been left to his young protégé, Vin, the former street urchin who is now the most powerful Mistborn in the land, and to the idealistic young nobleman she loves.',
      numberPages: 781,
      numberChapters: 58,
      dimensiones: [5.5, 8.2],
      peso: 1.1,
    },
  },
  {
    bookId: '2a',
    title: 'The Great Hunt',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659905799i/233649.jpg',
    pages: '681',
    size: '2800000',
    year: '1990',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '2b3c4d5e6f7g8h9i0j1a',
      description:
        "The Forsaken are loose, the Horn of Valere has been found and the Dead are rising from their dreamless sleep. The Prophecies are being fulfilled - but Rand al'Thor, the shepherd the Aes Sedai have proclaimed as the Dragon Reborn, desperately seeks to escape his destiny.",
      numberPages: 681,
      numberChapters: 50,
      dimensiones: [6.1, 9.2],
      peso: 1.3,
    },
  },
  {
    bookId: '3ia2b',
    title: 'The Dragon Reborn',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1659905781i/34897.jpg',
    pages: '624',
    size: '2600000',
    year: '1991',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '3c4d5e6f7g8h9i0j1a2b',
      description:
        'The Dragon Reborn—the leader long prophesied who will save the world, but in the saving destroy it; the savior who will run mad and kill all those dearest to him—is on the run from his destiny.',
      numberPages: 624,
      numberChapters: 56,
      dimensiones: [6.1, 9.2],
      peso: 1.2,
    },
  },
  {
    bookId: '4',
    title: 'The Shadow Rising',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1638239837i/9539.jpg',
    pages: '701',
    size: '2900000',
    year: '1992',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '4d5e6f7g8h9i0j1a2b3c',
      description:
        'The fourth book in The Wheel of Time series, exploring the journeys of the main characters as they prepare for the Last Battle.',
      numberPages: 701,
      numberChapters: 58,
      dimensiones: [6.1, 9.2],
      peso: 1.5,
    },
  },
  {
    bookId: '5d',
    title: 'The Fires of Heaven',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327866286i/13895.jpg',
    pages: '988',
    size: '4000000',
    year: '1993',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '5e6f7g8h9i0j1a2b3c4d',
      description:
        'The fifth book in The Wheel of Time series, detailing the efforts of Rand and his allies as they face increasing threats from the Forsaken.',
      numberPages: 988,
      numberChapters: 56,
      dimensiones: [6.1, 9.2],
      peso: 1.8,
    },
  },
  {
    bookId: '63ddede',
    title: 'Lord of Chaos',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1480096417i/35231.jpg',
    pages: '1011',
    size: '4100000',
    year: '1994',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '6f7g8h9i0j1a2b3c4d5e',
      description:
        "In this sequel to the phenomenal New York Times bestseller The Fires of Heaven, we plunge again into Robert Jordan's extraordinarily rich, totally unforgettable world:On the slopes of Shayol Ghul, the Myrddraal swords are forged, and the sky is not the sky of this world ...",
      numberPages: 1011,
      numberChapters: 61,
      dimensiones: [6.1, 9.2],
      peso: 1.9,
    },
  },
  {
    bookId: '7g6f',
    title: 'A Crown of Swords',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1358542379i/13890.jpg',
    pages: '880',
    size: '3600000',
    year: '1996',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '7g8h9i0j1a2b3c4d5e6f',
      description:
        "The seventh book in The Wheel of Time series, featuring Rand's quest to secure the throne of Cairhien and his fight against the Seanchan.",
      numberPages: 880,
      numberChapters: 41,
      dimensiones: [6.1, 9.2],
      peso: 1.7,
    },
  },
  {
    bookId: '8he6f7g',
    title: 'The Path of Daggers',
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1390508613i/140974.jpg',
    pages: '672',
    size: '2700000',
    year: '1998',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '8h9i0j1a2b3c4d5e6f7g',
      description:
        "The Seanchan invasion force is in possession of Ebou Dar. Nynaeve, Elayne, and Aviendha head for Caemlyn and Elayne's rightful throne, but on the way they discover an enemy much worse than the Seanchan.",
      numberPages: 672,
      numberChapters: 31,
      dimensiones: [6.1, 9.2],
      peso: 1.4,
    },
  },
  {
    bookId: '9i0jh',
    title: "Winter's Heart",
    imgUrl:
      'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1667248191i/13891.jpg',
    pages: '668',
    size: '2700000',
    year: '2000',
    publisher: 'Tor Books',
    language: 'English',
    type: 'epub',
    authors: 'Robert Jordan',
    category: 'Fantasía',
    detail: {
      bookId: '9i0j1a2b3c4d5e6f7g8h',
      description:
        "Rand is on the run with Min, and in Cairhein, Cadsuane is trying to figure out where he is headed. Rand's destination is, in fact, one she has never considered.",
      numberPages: 668,
      numberChapters: 35,
      dimensiones: [6.1, 9.2],
      peso: 1.4,
    },
  },

];
